### PR TITLE
Updating fast unifrac benchmark with pycogent fast unifrac included

### PR DESCRIPTION
**Pull request by mortonjt**
Here are the fast unifrac benchmarks.

I haven't been able to run the very last benchmark - it takes a really long time to run in notebooks.

### CODE REVIEW

**Comment by wasade** [comment]
Can you verify that the pycogent implementation is pruning the tree? If so, then the skbio implementation is like 2 orders of magnitude faster...

**Comment by mortonjt** [comment]
...

That was quite lame.

It should have been pruning the tree. Rerunning the tests

**Comment by wasade** [comment]
Ah! Well, still useful to see as the other runs include both.

**Comment by wasade** [comment]
hmm... well, it looks to be confounded some. `fast_unifrac` from cogent has `make_subtree=True` by default, so it is pruning but the cost of the prune is included in the runtime for the function call. Interesting. Ya, it would I think be useful to provide a pruned (sheared) tree as would better match the sheared tree runs (perhaps with `make_subtree=False` when doing so), and to use the full tree (with `make_subtree=True`) when doing the full tree runs. Does that make sense?

**Comment by wasade** [comment]
regardless, this is looking quite a bit faster.

**Pull request closed without merging**
